### ISSUE TITLE
default fold and unfold key bindings has no function

### ISSUE THREAD

**Issue by thenewvu** [20Tauri/DoxyDoxygen#1]
Hello,

The first, your plugin is awesome, it makes my life easier, thank you so much for that. But, there is an annoying thing that your plugin overwrote default fold and unfold key bindings, and the result is they has no function on my side.

Could you please change it to avoid the conflict ?

Thank you,

**Comment by 20Tauri** [comment]
Thanks you for feed back,

DoxyDoxygen catches the default folding comment to make it work with single line comment.
But, you are right, there's a bug the this functionnaly. The key binding is incorrect (wrong scope). The plugin catches key even outside comments....
This problem is solved in 0.9.1 (I just relase it, you may download using package control in a short while)

You probably already know (and it's no more necessary), but to restore a standard behaviour, you may copy default key bindings in your user key bindings

```
    { "keys": ["ctrl+shift+["], "command": "fold" },
    { "keys": ["ctrl+shift+]"], "command": "unfold" },
```

Thanks again to make this software better
