### ISSUE TITLE
Force style in .sol docs.

### ISSUE THREAD

**Issue by mesqueeb** [20Tauri/DoxyDoxygen#101]
I have troubles with **.sol docs**.
I only am able to get a `//` doxygen instead of my preferred method: `/**` for the **.sol docs**.

I tried changing some settings but I was unable to find how to change this.
The command for switching styles did nothing: `Super+Shift+Alt+Q` (mac)

I'm on _Sublime Text 3_ and want `/**` for .sol docs. Does anyone have any advice?

**Comment by 20Tauri** [comment]
What means '.sol docs' ? `Solidity Ethereum` ?
If yes, this issue is caused by the [Comments.tmPreferences](https://github.com/davidhq/SublimeEthereum/blob/master/Comments.tmPreferences) file. It forces a space after `/*`. Next release of sublime text will embed is own definition of comment style to solve this issue.

Note that Solidity is not supported... and there's currently some issues also due to the poor syntax. For example returns value are seem as parameter. May be fix in next release

**Comment by mesqueeb** [comment]
Dear @20Tauri 
Thank you for your detailed answer! I indeed meant `Solidity Ethereum`.
I am looking forward for the next release!

**Comment by 20Tauri** [comment]
Implemented in 0.64.0. Available from now in evolution branch

**Comment by mesqueeb** [comment]
Great! I'll update my Sublime packages!
