### ISSUE TITLE
No longer able to install DoxyDoxygen

### ISSUE THREAD

**Issue by fgimian** [20Tauri/DoxyDoxygen#109]
Hey there, since recently, Sublime Text fails to install DoxyDoxygen using Package Control.

Here's the output from my console:

```
Package Control: Error downloading package. HTTP exception InvalidCertificateException (Host github.com returned an invalid certificate ([SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:548))) downloading https://github.com/20Tauri/DoxyDoxygen/releases/download/0.65.2/ST3_DoxyDoxygen.sublime-package.
error: Package Control

Unable to download DoxyDoxygen. Please view the console for more details.
```

Any help would be appreciated
Fotis

**Comment by profi200** [comment]
Same issue. I reported this on the Package Control repo because i think it's something with Package Control.

https://github.com/wbond/packagecontrol.io/issues/103

**Comment by 20Tauri** [comment]
Already discussed here https://github.com/20Tauri/DoxyDoxygen/issues/103.
The reference may be found on the main page on both Package Control and GitHub

The problem is in the Python download of Package Control that don't support TLS 1.2. You can switch to "curl". The problem occured mainly on Linux and OS/X. People who is XP/Vista, may download a Fix (see issue 103)

I nothing work, you can also download manually the package from this site (click on "[releases](https://github.com/20Tauri/DoxyDoxygen/releases)").
For security reason, please never download a version from an unknown source

**Comment by fgimian** [comment]
Thanks so much for the reply, apologies I missed the other info, closing the issue now 😃

**Comment by profi200** [comment]
@20Tauri Commenting on this since the workaround in the other issue you linked to doesn't work here. With curl as first option it now says "The package 'DoxyDoxygen' is not available".

Edit:
Nevermind. It worked when i tried Package Control --> Install package. For some reason automatic install is broken though.
