### ISSUE TITLE
//! style Doxygen comments in C++

### ISSUE THREAD

**Issue by VorpalBlade** [20Tauri/DoxyDoxygen#11]
This is either a feature suggestion or a report of lacking documentation for the configuration file (in case this is already possible to do):

The project I work on (C++) uses the following Doxygen formatting style:

```
//! @brief Something
//!
//! @param a            Whatever
//! @param bcdeLongName Whatever
//!
//! @return Returns something
bool myFunction(int a, long bcdeLongName);
```

I have not been able to get anything like this for the autogenerated value. The best I managed is:

```
   //!
   //! @brief      { function_description }
   //!
   //! @param[in]  a             { parameter_description }
   //! @param[in]  bcdeLongName  { parameter_description }
   //!
   //! @return     { description_of_the_return_value }
   //!
   bool myFunction(int a, long bcdeLongName);
```

There are two issues here:
1. The extra "//!" at the start and end. Is it possible to configure it to not generate those for C++? To even get //! (instead of /*\* style) comments for C++ to begin with I changed the first entry in "prefered_comments_styles". Is there a better way to do this?
2. The [in] following param. We don't use that notation. Can it be disabled?

**Comment by 20Tauri** [comment]
### Extra "//!"

To remove blank line, you have to change the layout:

``` javascript
{
    "block_layout": {
        "Doxygen": [
            //"",     this line force the top blank line, you have to comment/remove it
            "@brief",
            "",
            "@param",
            "",
            "@return",
            "",
            "@throws"
            // ""    this line force the bottom blank line, you have to comment/remove it
}
```

Unfortunaly, in your case, this will not work in versions prior to 0.14.2 : Doxygen (evolution).

### [in] [out] [in, out]

I have just add an option "doxygen_discard_param_directions" to discard direction indicator.
In version prior to 0.14.2, a way to do this, is to overide the doxygen DocStyle.
By chance "Doxygen_contrib_HeaderDoc" is close to your need

Installing "Doxygen_contrib_HeaderDoc" and changing 

``` javascript
        [
            [ "c++", "c", "cuda-c++" ],
            "LanguageCpp",
            [ "Doxygen" ]
        ],
```

To

``` javascript
        [
            [ "c++", "c", "cuda-c++" ],
            "LanguageCpp",
            [ "DoxyDoxygen_contrib_HeaderDoc", "Doxygen" ]
        ],
```

Should works
It's a non trivial but powerful recipe

I you want to try it, don't forget to change "block_layout" -> "HeaderDoc" instead of "block_layout" -> "Doxygen" for point 1

### Bonus

You probably also have to set

``` javascript
    "prefered_tabs_sizes": [ 1 ],
    "min_spaces_between_columns": [ 1 ],

```

To remove extra spaces between column
