### ISSUE TITLE
[C++] unable to work with operator overload with template return type

### ISSUE THREAD

**Issue by jasjuang** [20Tauri/DoxyDoxygen#110]
Please see the below minimal code to reproduce the problem,

```
class Sample
{
 public:
 	
  T operator[](int a) 
  {
     // do something
  }
};
```

If I click the function and do alt+Q it actually creates the template doxygen documentation for the class instead of the operator overload like the below.

```
/**
 * @brief      Class for sample.
 */
class Sample
{
 public:
 	
  T operator[](int a) 
  {
     // do something
  }
};
```

while I am expecting the template doxygen documentation to be generated for the function overload like 

```
class Sample
{
 public:
 	
  /**
   * @brief      { operator_description }
   *
   * @param[in]  a     { parameter_description }
   *
   * @return     { description_of_the_return_value }
   */
  T operator[](int a) 
  {
     // do something
  }
};
```

I did some tests and the below scenarios works

```
class Sample
{
 public:

  int operator[](int a) 
  {
     // do something
  }
};
```
```
class Sample
{
 public:

  T func(int a) 
  {
     // do something
  }
};
```

Weirdly enough this also works too

```
class Sample
{
 public:
 	
  T &operator[](int a) 
  {
     // do something
  }
};
```

It seems like it's the combination of template return type and operator overload that breaks it, and without the reference. It would be great if doxydoxygen can handle this scenario!

**Comment by 20Tauri** [comment]
When you replace 'T' by 'int', 'operator' probably switch is color.
Why, because the internal parser of SublimeText no longer detect it.
Try <kbd>Ctrl</kbd>+<kbd>R</kbd> to see the difference.

DoxyDoxygen don't use his internal parser to detected method declaration (for performance reason). So please contact the SublimeText team to solve it (or modify the grammar yourself)

To make DoxyDoxygen work, please not use <kbd>Alt</kbd>+<kbd>Q</kbd> in this specific case, use the alternave method `/**`, then <kbd>Enter</kbd>

**Comment by jasjuang** [comment]
Thanks for the explanation. I will file an issue to sublime.
