### ISSUE TITLE
Use HTTPS

### ISSUE THREAD

**Issue by francislavoie** [20Tauri/DoxyDoxygen#111]
Your docs site/payment page don't use HTTPS. I don't feel comfortable paying (even if actual payment is via Paypal over HTTPS) when the site isn't secure. I don't want to give my information on an insecure form. It's now dead-easy to add HTTPS to your site with Let's Encrypt. Please do so.

**Comment by 20Tauri** [comment]
Thank you for the suggestion.

Security is really important. I agree. On download, the plugin is HTTPS with TLS 1.2. This provides a high security level (and a [problem with package control for some users](https://github.com/20Tauri/DoxyDoxygen/issues/103)). This avoid code injection that may compromise your security

For the website, the problem is not the certificate but the server that host it. It's not currently possible to switch to HTTPS on it. There's no really security problem with this (except that someone can intercept your email address but don't forget that github exposes your email address... easier way to get it !). If the number of registered users grow significatly, I will consider switching server.

If you don't feel secure on this site, you can use the button at the [bottom of the github page](https://github.com/20Tauri/DoxyDoxygen), this button goes directly to paypal. I will use the paypal contact email in this case. It's easier but some users have outdated contact paypal email (form solve this king of problem).

Regards,

**Comment by 20Tauri** [comment]
Is the [direct link on paypal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=GXEEET3XT3VYG) meet your needs ?
