### ISSUE TITLE
Internal auto-complete inhibites sublime auto-complete on RST files

### ISSUE THREAD

**Issue by KuttKatrea** [20Tauri/DoxyDoxygen#121]
When editing a RST file, when pressing <kbd>Ctrl+Space</kbd> to get autocompletion of words, DoxyDoxygen says there are no completions (blocking the default words completion of sublime).

There are no preferences on DoxyDoxygen to allow integrating doxydoxy autocompletion with default autocompletion of Sublime Text.

**Comment by 20Tauri** [comment]
Thanks for reporting,
Unfortunatly not.
In the [lastest version 0.68.2](https://github.com/20Tauri/DoxyDoxygen/releases) (evolution), DoxyDoxygen will no longer inhibit the others completion.
If nobody report me trouble, that will be the new default settings. Otherwise, in will add an option.
Regards,

**Comment by KuttKatrea** [comment]
It seems to work just fine, thanks!
