### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by Doc999tor** [20Tauri/DoxyDoxygen#126]
Any plans to support TS? 
DoxyDoxygen could read the types from class/function declaration and substitute to `{<type>}` fields

**Comment by 20Tauri** [comment]
TypeScript is already supported throught the generic parser.
This parser wasn't support type detection... Template weren't correctly supported...
All those problem will be fixed in the next release

Also detected. The constructor detection is not currently support... But the bug is in the syntax file.

Probably available next week in evolution branch and in 2 months in the regular branch
