### ISSUE TITLE
What's the issue with ST's builtin Perl?

### ISSUE THREAD

**Issue by deathaxe** [20Tauri/DoxyDoxygen#132]
> Sublime Text 3207 known issues: Perl no longer work properly with syntaxes included in Sublime Text 3200 (the problem is in the syntax file)

Would you mind opening an issue at https://github.com/sublimehq/Packages/issues with information about why and how the builtin Perl syntax causes issue?

Maybe someone finds the time to fix it?

Maybe fixed by https://github.com/sublimehq/Packages/pull/1959?

**Comment by 20Tauri** [comment]
For example, this one fails:
```perl
sub mysplit(Rule $pat? = rx/\s+/, Str $expr? = $_, Int $lim? where $^lim >= 0) {
}
```

In this second example, let the '*' in the parameter name look discussable
```perl
sub somefunction($a, $b, :$c, :$d, *@e) {
}
```

I'm not a Perl developer, so I let the real Perl developers open the issue on SublimeHQ.
And usually bugs are fixed by the community (I only help for more complex problem lie API break)
My Perl warning is only here to avoid users to report me problem that are not directly in this plug-in.
Perhaps is already report... I don't know...

If you currently experiment some problems with this plug-in using Perl syntax, simply give me the actual and the expected result.
I will add it in my test suite.

If you give me examples and if the SublimeHQ team or the Perl maintainer of the syntax is interested in, I can post here the test-suite.
As it will be implemented at high level everyone that have DoxyDoxygen installed can run it.
Can be a good way to check the syntax files...

**Comment by deathaxe** [comment]
Actually it was me, who wrote the current implementation of the Perl syntax. Hence I am interested in detailed information about the issue to help avoiding the issues you encountered. I don't know about the schedule about when such a PR will be merged though.

**Comment by deathaxe** [comment]
With a quick check of your first example I'd argue `rx//` not to be a documented function. It's not listed at https://perldoc.perl.org Hence the next `s` is matched as substitution function with `+` as argument separator.

```perl
sub mysplit(Rule $pat? = /\s+/rx, Str $expr? = $_, Int $lim? where $^lim >= 0) {
}
```
`rx` are regexp flags and would need to be placed at the end of the term.

According to Perl's output I'd even argue it's not a valid perl function at all.

```
Malformed prototype for main::mysplit: Rule $pat? = rx/\s+/, Str $expr? = $_, Int $lim? where $^lim >= 0 at test_format.pl line 26. 
```

**Comment by 20Tauri** [comment]
My example was taken from [wikipedia](https://fr.wikipedia.org/wiki/Perl_6).
Note that it refer [Perl6](http://www.perl6.org/) and you refer Perl5

Note that $expr and $lim are optional parameters also introduced with Perl 6
But you are more experimented in Perl language than I.
I haven't Perl6 installed to make the check...

**Comment by deathaxe** [comment]
The current builtin Perl.sublime-syntax does not support Perl6 so far.

**Comment by 20Tauri** [comment]
With Perl syntax, on a comment line, the end of line is not considered as a part of the comment.
Press <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> before and after the last character to see this uncommon behavior.

This breaks the comment completion on DoxyDoxygen. It's minor and in the next release (unreleased) I've added a special case to handle this. But, you can be interested in this feedback.

**Comment by deathaxe** [comment]
This issue is fixed in https://github.com/sublimehq/Packages/pull/2048

It also caused normal completions to be triggered at the end of line of comments, which is unwanted. Hopefully helps you, too, once it's merged and released. :-)
