### ISSUE TITLE
Default "ctrl+shift+]" key binding does not unfold block comments

### ISSUE THREAD

**Issue by DiegoAlpizar** [20Tauri/DoxyDoxygen#133]
This is the dafault key binding that I have:
```json
{
	"keys": ["ctrl+shift+]"],
	"command": "doxy_fold_comments",
	"args": { "action": "unfold" },
	"context": [
		{ "key": "selector", "operator": "equal",  "operand": "comment.line", "match_all": true } // comment.line, comment.block
	]
},
```
It has "comment.line" as the context selector, which I overloaded with this custom key binding:
```json
{
	"keys": ["ctrl+shift+]"],
	"command": "doxy_fold_comments",
	"args": { "action": "unfold" },
	"context": [
		{ "key": "selector", "operator": "equal",  "operand": "comment", "match_all": true } // comment.line, comment.block
	]
},
```
This one has only "comment" as the context selector just like the default key binding for "ctrl+shift+["

```json
{
        "keys": ["ctrl+shift+["],
        "command": "doxy_fold_comments",
        "args": { "action": "fold" },
        "context": [
            { "key": "selector", "operator": "equal",  "operand": "comment", "match_all": true } // comment.line, comment.block
        ]
},
```

Is it the intended idea ?
Do I have a wrong/corrupted default key map file ?

I send a report from within ST using the integrated agent.

Thank you for this package. I installed it just today but I'm sure this is an awesome day to day tool!

**Comment by 20Tauri** [comment]
Thanks you for reporting Diego,

You are right, the default binding is wrong due to the selector scope.
Even when fixed on my side, your given example (javascript)still don't work.

The TypeScript package (!?) catch the binding too and conflict DoxyDoxygen.
This can be seen activating the logs with `sublime.log_commands(True)`

In all cases, put the keybind in the user profil (highest priority) fix the problem.

I will update the documentation (to explain the conflict) and fix this bug in the next release.
But in cannot fix the conflit, so your keybinding is the right fix for you and and JavaScript / TypeScript users.

Thanks again

**Comment by 20Tauri** [comment]
0.71.0 is now released on the evolution branch (sorry for the loooong delay)
Will be pushed in the regular branch next week
