### ISSUE TITLE
autocomplete not working

### ISSUE THREAD

**Issue by rgokul** [20Tauri/DoxyDoxygen#138]
I just installed this plugin. However I cant get auto completion to work. I dont see any settings in default doxydoxygen preference for auto_complete_selector that I can override in user settings. Can you please enhance documentation?

**Comment by 20Tauri** [comment]
According to the documentation, the setting to enable is [completion_enabled](http://20tauri.free.fr/DoxyDoxygen/v2/page_customization.php?highlight=completion_enabled)

However some issues are known in Lua, Swift, TypeScript and Perl languages cause completions don't work when cursor was at the end of a comment line (https://github.com/20Tauri/DoxyDoxygen/issues/132, https://github.com/sublimehq/Packages/issues/2127)
I will add a workaround in the next release to handle those cases

Can you add an example of what doesn't work. Including:
   - the language used
   - the docstyle used
   - the text before the cursor, when you press <kbd>Ctrl</kbd>+<kbd>Space</kbd>

**Comment by rgokul** [comment]
I am using it for the C language and doxygen style. When I added a new function into my file and I tried to add its doxygen I see that /** Enter worked. Next I filled brief. Enter. Typed @. no suggestions received. I typed @details pressed tab. It filled out the template for @details. Pressed enter and tried to type @ again for note. No suggestion of available commands.

```
/**
 * @brief      init foo
 * @details    init foo explicitly
 * @note       blH
 *
 * @return     { description_of_the_return_value }
 */
status_t foo_init(void);
```

**Comment by 20Tauri** [comment]
Tested on both, Sublime Text 2 & 3.
For the first test, as I've the sublime setting `auto_complete_selector` set to its default (completion disabled in comments), I've to press <kbd>Ctrl</kbd>+<kbd>Space</kbd> to have the possible choices
When I enter `@details` then <kbd>Tab</kbd>, It works as expected

Have you try to enter `@d`, then press <kbd>Ctrl</kbd>+<kbd>Space</kbd>.
In this case, I have severals suggestions. The DoxyDoxygen ones and the C ones (`do` `def`). If you have no suggestion, the problem is probably not DoxyDoxygen

**Comment by 20Tauri** [comment]
Have you try my suggestion ?
Have you any idea about the way to enhance documentation ? The `auto_complete_selection` tip is in the documentation... But you have probably miss it. What section or keywords you have look for to try to find an answer to your question....

This will help to improve the documentation
