### ISSUE TITLE
Request: lower border style 

### ISSUE THREAD

**Issue by JohannesMP** [20Tauri/DoxyDoxygen#17]
Currently the `prefered_comments_styles` setting allows us to customize the top and left border of Documentation blocks.

It would be nice to have the option of defining the lower edge of the block to allow us to create doxygen blocks such as:

```
/*------------------------------------------*//**
 * @brief   stuff
 *---------------------------------------------*/

/********************************************//**
 @brief      stuff
 ***********************************************/

/////////////////////////////////////////////////
/// @brief  stuff
/////////////////////////////////////////////////
```

Where the corresponding styles just includes an optional third line that defines the bottom edge:

```
...
"prefered_comments_styles": [
    [
        "/*------------------------------------------*//**",
        " *",
        " *---------------------------------------------*/"
    ],
     [
        "/********************************************//**",
        " ",
        " ***********************************************/"
    ],
     [
        "/////////////////////////////////////////////////",
        "///",
        "/////////////////////////////////////////////////"
    ],
...
```

---

Ideally I'd like to be able to create a comment that looks like:

```
/*!**********************************************
  @brief      stuff
************************************************/
```

Which would require a combination of this issue and issue #16

**Comment by 20Tauri** [comment]
It's really a complex subject...

DoxyDoxygen make a difference between "commenting style" ("/**") and "block_layout" ("@brief").
Currently a "block_layout" is link to a DocStyle (Doxygen in your case). There's already an annoying limitation as we can use 2 DocStyles for a same language (ex: JsDoc3 and GoogleClosure).

But, I not sure that mixing "commenting style" and "block_layout" is the best solution.
For now (may change), I prefer to allow to force a "block_layout" in a specific "profil"... Because usefull cases are probably rares...

Capability to configure footer on command.block" (only !) will be considered.
Not a real problem, but it may cause problem to others tools.

Subject is open

**Comment by 20Tauri** [comment]
0.20.0 has been released and adds this feature...

**Comment by JohannesMP** [comment]
With 0.20.0, the following settings:

```
"prefered_comments_styles": [
    [
      "/*!********************************",
      "    ",
      "**********************************/"
    ],
```

produce the following output (`|` added to indicate left margin): 

```
|/*!********************************
|     @brief      { function_description }
|     @return     { description_of_the_return_value }
|    **********************************/
```

I feel that the spacing of the last row is incorrect here. It appears as though the 'left margin' section of `prefered_comments_styles` is being prepended to the 'bottom margin' section.

I feel that the provided style should result in this output instead:

```
|/*!********************************
|     @brief      { function_description }
|     @return     { description_of_the_return_value }
|**********************************/
```

**Comment by 20Tauri** [comment]
Sorry, it was a lack of documentation... But, your expected behavior is more consistent than mine...
So, I decide to no longer take care of "inner margin" for the "bottom style" and let the user define his own.

0.20.2 (just released) will provide the expected behavior.

It still a limitation. "bottom style" can only be applied on command block. Following will be rejected

```
     [
        "/////////////////////////////////////////////////",
        "///",
        "/////////////////////////////////////////////////"
    ],
```

Note: In 0.20.0, `preferred_comments_styles` should be preferred over `prefered_comments_styles`
