### ISSUE TITLE
Auto-indent with tabs not working

### ISSUE THREAD

**Issue by teroyks** [20Tauri/DoxyDoxygen#2]
If the code is indented with tabs, the indentation of a new comment line is wrong.

Example: method name is indented with one tab, after which there is one space and \* for a comment line. Pressing enter on this line creates a new comment line indented with two spaces, not tab+space.

**Comment by 20Tauri** [comment]
Thanks you for reporting

I reproduce the problem in two contexts:
- comment continuation
- comment reformating (but without snippets only)

Here two examples

``` javascript
    /*----------------------------------------------------------------------*//**
     * { function_description }
     *
  *
     * @return     {number}  { description_of_the_return_value }
     */
    test: function() {
        return 1;
    }


    /**
  * blabla (pressing alt+q)
  */
    void methodName()
    {
    }

```

When tabs are present, sublime text behaviour is strange, "view.rowcol()" returns the number of characters instead of the real column.(3 for tab+space+\* instead of 6 if tabsize is 4)

Both problems are fixed in 0.12.2 (just released).
Do not hesitate to recontact me if you experiment others issues
