### ISSUE TITLE
Maintaining indentation with code

### ISSUE THREAD

**Issue by JohannesMP** [20Tauri/DoxyDoxygen#21]
When first creating a documentation block with `Super`+`Alt`+`Q` (on mac), its indentation will be in line with that of the function it is commenting. This is desirable.

However on further updates with the same command, the documentation block will be moved to the left-most position.
![doxygen10](https://cloud.githubusercontent.com/assets/662874/10065279/3f08a32a-6238-11e5-9c68-9e1479293c9b.gif)

I feel that, once created, the documentation block should remain at its current level of indentation, and updating it should _not_ shift it to the left margin.

Personally, I like having the option of indenting my code to the same level as my function, such as when inside of a namespace.

Perhaps an option could be added that overrides indentation of all code blocks, but by default I want it to just use whatever the level of indentation of the code that follows it is.

**Comment by 20Tauri** [comment]
Your expected behaviour is my expected behaviour too...
DoxyDoxygen is designed to preserve comment (even style in fact).

I cannot reproduce your test case... and it's a major bug.
I have try to change sublime text options (indent, tab_to_space...). In all cases, it works fine for me.

From palette command, please select "DoxyDoxygen: Select Commands", then "Doxy". Our command should be selected (but NOT the space before). If it's not the case, I'm interested by the syntax scope just before the comment.

As the previous test will probably succeed (we use nearly the same version of Sublime and you use the lastest DoxyDoxygen (evolution) version). I will need both
- your DoxyDoxygen settings
- your sublime settings (to be sure to be in the same context)

As others plugins may affect the behaviour. If you have time, you may also test with a portable version of Sublime (with no other plugin and with default settings)... This will help to find which parameter and/or which plugin cause the error
I've done this test on my side with a 3084 version. Works fine too for me (but I've no OS/X)

**Comment by JohannesMP** [comment]
I've tried to do a clean install of Sublime and was unable to reproduce this issue. It's probably safe to assume that this was an issue with another package.

**Comment by 20Tauri** [comment]
A really strange problem.
If you can reproduce it, I'm really interested
On my side, I will improve the comment detection to be more "reliable" if a sublime-syntax decide to start a comment by a space...

**Comment by 20Tauri** [comment]
Not reproductable and a security have been added (when used with incorrect syntaxes)
