### ISSUE TITLE
Is it possible to disable default parameter description

### ISSUE THREAD

**Issue by jasjuang** [20Tauri/DoxyDoxygen#49]
Suppose I have a function called

```
  void test(const int red, const int blue);
```

Now typing alt+Q yields

```
/**
 * @brief      { function_description }
 *
 * @param[in]  red   The red
 * @param[in]  blue  The blue
 */
  void test(const int red, const int blue);
```

I remember before it was

```
/**
 * @brief      { function_description }
 *
 * @param[in]  red   { parameter_description }
 * @param[in]  blue  { parameter_description }
 */
  void test(const int red, const int blue);
```

with the parameter_description highlighted ready for me to add my own description.

Is it possible to go back to the old way? The reason why the old way is better is because after typing alt+q -> type in first parameter description -> alt+q type in second parameter description -> and so on... the flow is very smooth, no mouse action is needed.

The new way I have to alt+q -> use mouse to highlight "the first parameter" -> backspace delete -> type in first parameter description -> use mouse to highlight "the second parameter" -> backspace delete -> type in second parameter description -> and so on... which is a lot slower.

**Comment by 20Tauri** [comment]
To disable autofill, update your configuration file with one of the following line
- to disable the default rules:  `"autofill_rules_default": [],`
- to disable all rules: `"autofill_reliability_percentage": 0,`

The first method was explain in the default configuration file but the this file is probably not the best way to provide documentation.

Thank for your feedback, I've post a survey about this feature few month ago... but have only 2 replies... Both interesting, but opposite. I also like <kbd>Alt</kbd>+<kbd>Q</kbd> but you can simply use  <kbd>Tab </kbd> to go to the next item to document... On comment creating, it's probably a more efficient way to do (less keys to press)

If you prefer to have no description, you can try:

``` json
    "autofill_rules": [
        {
            "parameter_description": [
                "."
            ]
        }
    ],
```

I'm not sure of the best default setting... The current one try to encourage to add information about parameter. In your example: 
- is `red` represents the intensity of the red component of the color ?
- what's is the range (0-255) ? why an int in the way ?
- is 255 mean opaque ?
- there's no `green` parameter, is `red` the color of the button pressed ?
- what are the possible value in that case ?...

That way, I choose to add `The`, according me `The` encourage to add something...

This subject is really interesting... And creating the best rules (language independent, because sometime function name are not in english) is an improvement way...

**Comment by jasjuang** [comment]
Interesting how tab works specially on doxydoxygen. I never knew it. With tab working this way I am happy with the current setup.

I can also confirm that "autofill_rules_default": [] reverts back to the old days for the default parameter description.

Thanks a lot for the answer!

**Comment by jasjuang** [comment]
Actually I still prefer the old way.

Because tab no longer work when I move the cursor out to do something else then comeback. It is only able to scroll through the parameter descriptions when I invoke alt+Q initially.

**Comment by 20Tauri** [comment]
Thanks for your feedback...

It focus on this main question: When a description should be considered as set (<=> untabbable) ?
- when there's a description (current) ?
- when there's a manual description ?
- ...
- always ?

Perhaps I will open a survey on it.

**Comment by jasjuang** [comment]
I think it should be when there's a manual description

**Comment by 20Tauri** [comment]
I've experimented it in the last "evolution" version...
We will see users feedback...
