### ISSUE TITLE
Shortcuts can't be used on OSX

### ISSUE THREAD

**Issue by ncoden** [20Tauri/DoxyDoxygen#5]
Alt + Q / EOL / Ctrl + Shift + [ or ]...
Theses shortcuts can't be used on OSX (at least not with my Azerty)
Can you use "Super" shortcuts (Ctrl on Windows and Cmd on OSX) ?

**Comment by 20Tauri** [comment]
What is the usual shortcut to wrap line on OSX ?
What is the usual shortcut to fold/unfold ?
What is the usual key to go to end-of-line ?

Those may be found from palette in "preference: keys bindings default"
And "DoxyDoxygen"'s ones may be overload by "preference: keys bindings user"

It's will be great if you can send me your fixed version. Because I've no Mac to test it.
Merci d'avance !

**Comment by ncoden** [comment]
wrap_line : super (Cmd) + alt + q (checked)
fold/unfold : super (Cmd) + alt + [ / ](can't check, I have a modified keyboard, with "[" and "]" already requiring Alt)
end of line : Fn + Right (checked)

I don't understand what you mean by "Fixed version"
French too ? :)

**Comment by 20Tauri** [comment]
Thanks,

"doxy_comment_nearest_entity" et "doxy_reformat" were already bound to "super+alt+q"... So it should already work (strange)

I haved fixed the documentation and the others keys.
Version has been released (0.13.6)... For now, only available for "Doxygen (evolution)" version via package control. But can also be installed manually from https://github.com/20Tauri/DoxyDoxygen/releases/tag/0.13.6

Default bindings can be found in menu "package settings -> DoxyDoxygen -> Key Binding (OSX) - Default"
Oui ;)
