### ISSUE TITLE
Alt + Q not working with WrapLinePlus

### ISSUE THREAD

**Issue by niosus** [20Tauri/DoxyDoxygen#53]
It seems like the default key binding is not working. 

By default Sublime does code wrapping when <kbd>Alt</kbd>+<kbd>Q</kbd> are pressed.

**Comment by 20Tauri** [comment]
It's really strange... You can check your felling using those Sublime Text commands

``` python
sublime.log_input(True)
sublime.log_commands(True)
```

I'm interested in the command called... Maybe there's a conflit with another plugin
If the Sublime Text default binding is called, it's probably because of DoxyDxygen selector "source, text.html.cshtml, text.jade" doesn't match

It will be great is you can use the integrated agent.
- Move the cursor.
- Press <kbd>Alt</kbd>+<kbd>Q</kbd>
- Then right click, and select `DoxyDoxygen Report` -> `Anomaly Report`.
  A report will be displayed. Simply Add "Alt+Q" as description
- Then right click and select `>>> Send Report <<<`

**Comment by niosus** [comment]
Oh, the issue reported here is wrong. The actual issue is that I am completely and irreversibly stupid :)

Your documentation states:

> type `/**` and press <kbd>Enter</kbd>

I tried to press <kbd>Tab</kbd> instead. 

It works as expected when I am pressing <kbd>Enter</kbd>. So embarassing :)
Sorry for a false alarm.

**Comment by niosus** [comment]
Oh, it is a hard morning, sorry. I though I reported the issue that `/**` did not work... 

the <kbd>Alt</kbd> + <kbd>Q</kbd> is still there. I will gather the report now. Reopening.

**Comment by niosus** [comment]
The issue with <kbd>Alt</kbd> + <kbd>Q</kbd> is that it is clashing with another plugin for me. I use WrapLinesPlus plugin that uses the same key bindings. If I disable this plugin, <kbd>Alt</kbd> + <kbd>Q</kbd> behaves as expected for your plugin.

But anyway, by default, pressing <kbd>Alt</kbd> + <kbd>Q</kbd> in Sublime Text will trigger line wrap and your plugin shadows this. I don't know if it is worth changing the key binding (it will inevitably clash with something else), so I think it is more like an info. Sorry for bothering again.

**Comment by 20Tauri** [comment]
Thank you for reporting, I will add this conflict in the knowledge base

I've add this binding because the default sublime text seem to be designed for `text  scope rather than`source` scope.

You can easily rebind this shortcut and add <kbd>tab</kbd> in the user level binding (preference->key bindings - user). This will override the plugin ones.
