### ISSUE TITLE
Latest Dev Build of Sublime Text 3 Seems to Have Broke Something

### ISSUE THREAD

**Issue by aymaluser** [20Tauri/DoxyDoxygen#63]
reloading plugin DoxyDoxygen.Doxy
------==== DoxyDoxygen plugins loaded ====------
0 sub-modules to reload
Traceback (most recent call last):
  File "Doxy in /home/lab/.config/sublime-text-3/Installed Packages/DoxyDoxygen.sublime-package", line 151, in <module>
  File "Doxy in /home/lab/.config/sublime-text-3/Installed Packages/DoxyDoxygen.sublime-package", line 145, in import_doxy_object
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "0.52.0\ST3\TMP\doxy_libs__init__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "0.52.0\ST3\TMP\doxy_libs\DoxyBlock.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "0.52.0\ST3\TMP\doxy_libs\Translator.py", line 18, in <module>
AttributeError: 'module' object has no attribute 'parse'
error: DoxyDoxygen fails to import some files... Please restart SublimeText

**Comment by 20Tauri** [comment]
Thanks for reporting,

It's a problem with Python3 relative imports.
Not all plateforms seem to be affected... and probably not DoxyDoxygen specific
I will ask on the [Sublime Text forum](https://forum.sublimetext.com/t/dev-build-3121/22806/9)

**Comment by Jo2003** [comment]
I have the same problem on Ubuntu 14.04.

**Comment by ferhtgoldaraz** [comment]
Same here in ElementaryOS Loki

**Comment by 20Tauri** [comment]
Sorry for my late reply...

"urllib.parse" module is no longer available on Linux...
Look strange because still present on others plateforms.
Look definitively like a bug in Sublime Text...

Still really annoying... I will try to push a version that only disable network layer in this case (Translations will not work, but it's better then nothing...)

**Comment by 20Tauri** [comment]
We will probably still have the problem with the fresh 3122 Sublime Text version...

It will be great if you can check that

``` python
import  urllib.parse as url_parser
```

fails on your system and report it to the Sublime Text team to help them to solve the problem

To reduce the problem, in version 0.55.0 (evolution branches),  I now display an error (it is)... But I keep the plugin active. Translations will not work but main features will be present.
This version is not carefully tested... Feedback welcome...
I will do more tests tomorrow.

**Comment by adzenith** [comment]
3122 is still broken (Ubuntu 14.04):

```
>>> import urllib.parse as url_parser
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'parse'
```

**Comment by ferhtgoldaraz** [comment]
In my system (ElemnetaryOS Loki, based on Ubuntu 16.04 x64, and python 3.5.2) it works, so does in sublime's 3120.

In sublime 3122 it fails. Same as already described:

``` python
>>> import urllib.parse as url_parser
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'parse'
```

**Comment by ferhtgoldaraz** [comment]
Wait.

I just renamed my `"~/.config/Sublime Text 3"` Folder to start clean, and now it does not fail to find `parse` within `urllib`.
This is `sys.path`now:

``` python
>>> import sys
>>> sys.path
['/opt/sublime_text', '/opt/sublime_text/python3.3.zip', '/home/fer/.config/sublime-text-3/Packages']
```

This is my sys.path with my normal config (formatted the array for readability)

``` python
>>> import sys
>>> sys.path
[
    '/home/fer/.config/sublime-text-3/Packages/ssl-linux/st3_linux_x64/libssl-1.0.0',
    '/opt/sublime_text',
    '/opt/sublime_text/python3.3.zip',
    '/home/fer/.config/sublime-text-3/Packages',
    '/home/fer/.config/sublime-text-3/Packages/pygments/all',
    '/home/fer/.config/sublime-text-3/Packages/bz2/st3_linux_x64',
    '/home/fer/.config/sublime-text-3/Packages/backrefs/st3',
    '/home/fer/.config/sublime-text-3/Packages/markupsafe/all',
    '/home/fer/.config/sublime-text-3/Packages/python-markdown/st3',
    '/home/fer/.config/sublime-text-3/Packages/python-jinja2/all',
    '/home/fer/.config/sublime-text-3/Packages/mdpopups/st3',
    '/home/fer/.config/sublime-text-3/Installed Packages/Emmet.sublime-package',
    '/home/fer/.config/sublime-text-3/Installed Packages/Emmet.sublime-package/emmet_completions',
    '/home/fer/.config/sublime-text-3/Installed Packages/Emmet.sublime-package/emmet'
]
```

I'm gonna start removing folders from there until I find something useful to report here

**Comment by ferhtgoldaraz** [comment]
Wow. It wasn't any of those. But I can import it now by only removing `Package Control.sublime-package`. I don't think I can simply get away without that one. I'll try a few more things and report it to them or revert to 3120 for now

**Comment by ferhtgoldaraz** [comment]
Nothing. Clean install, as soon as I install package Control urllib no longer contains parse. I guess it's a package control bug.

**Comment by aymaluser** [comment]
Interesting ... that is something in the change list:  They added a menu item to install package control.  I don't know if it's related, but it could be.

**Comment by 20Tauri** [comment]
Thanks Fernando (ferhtgoldaraz). I see you have reported your analyze on [Sublime Text forum](https://forum.sublimetext.com/t/dev-build-3121/22806/64).

Even if 3122 is still broken, The new DoxyDoxygen version (0.55.0) is now usable on it... 
The version is now better tested, nothing special:
- [incorrect syntaxes files detected on 3115](http://20tauri.free.fr/DoxyDoxygen/v2/page_known_issues.php) still broken
- Translations will not be perform if `url.parse` cannot be imported

By the way, the best is probably to avoid those Sublime Text versions for now

**Comment by ferhtgoldaraz** [comment]
Nice!

Also, I just manually installed Package Control 3.2.0-beta2 (following the mentioned thread), and I can confirm everything works flawlessly with that Package Control version. Maybe once that version is available through `Preferences>Package Control` or the otherwise stable channels, this issue can be closed.

**Comment by 20Tauri** [comment]
Thanks,
I will update documentation `Known issues` section and add a specific warning when `urllib.parse` cannot be imported to refer this post...

**Comment by 20Tauri** [comment]
Now released on both versions

**Comment by saltthehash** [comment]
I am having the same issue and just wanted to point something out: (at least for me) urllib.parse isn't available on Python2 but it IS available on Python3:

```
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib.parse
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named parse
>>> 

```

```
Python 3.5.2 (default, Sep 10 2016, 08:21:44) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib.parse
>>> 
```

Also, how did everyone install Package Control 3.2.0-beta2? I cannot seem to find it anywhere. I tried adding the pre-release repository to Package Control but now that points to version 3.2.1 (https://packagecontrol.io/prerelease/packages.json), I suppose I'm a few days late since this was changed/updated just 2 days ago...

**Comment by 20Tauri** [comment]
Hi, There's no urllib.parse import when you use DoxyDoxygen from Pything2... `import urllib as url_parser`. As cannot be the seem, please look in the console to see your specific error.

As you have seen, Package control 3.2.1 is now released. So simply use package control to upgrade it. Also upgrade DoxyDoxygen. Then restart Sublime Text

But once again, the first is probably to look in the console (without the information, it's hard to help)

**Comment by dc-avasilev** [comment]
```
DoxyDoxygen fails to import `urllib.parse`...
Network functions will not work.

You can try to install Package Control 3.2.0-beta2+ to fix this issue (see https://github.com/20Tauri/DoxyDoxygen/issues/63 for details).

[OK:Button]

>>> import sys

>>> sys.path
['/home/username/.config/sublime-text-3/Packages/SublimeCodeIntel/arch', 
'/home/username/.config/sublime-text-3/Packages/SublimeCodeIntel/libs', 
'/home/username/.config/sublime-text-3/Installed Packages/Restructured Text (RST) Snippets.sublime-package/wcwidth', 
'/home/username/.config/sublime-text-3/Packages/ssl-linux/st3_linux_x64/libssl-1.0.0', 
'/opt/sublime_text', 
'/opt/sublime_text/python3.3.zip', 
'/home/username/.config/sublime-text-3/Packages', 
'/home/username/.config/sublime-text-3/Packages/pygments/all', 
'/home/username/.config/sublime-text-3/Packages/pathtools/all', 
'/home/username/.config/sublime-text-3/Packages/package_events/all', 
'/home/username/.config/sublime-text-3/Packages/watchdog/all', 
'/home/username/.config/sublime-text-3/Packages/backrefs/st3', 
'/home/username/.config/sublime-text-3/Packages/markupsafe/all', 
'/home/username/.config/sublime-text-3/Packages/python-markdown/st3', 
'/home/username/.config/sublime-text-3/Packages/pyyaml/st3', 
'/home/username/.config/sublime-text-3/Packages/python-jinja2/all', 
'/home/username/.config/sublime-text-3/Packages/mdpopups/st3', 
'/home/username/.config/sublime-text-3/Installed Packages/CTags.sublime-package', 
'/home/username/.config/sublime-text-3/Installed Packages/CTags.sublime-package/helpers', 
'/home/username/.config/sublime-text-3/Installed Packages/CTags.sublime-package', 
'/home/username/.config/sublime-text-3/Installed Packages/EditorConfig.sublime-package', 
'/home/username/.config/sublime-text-3/Installed Packages/Emmet.sublime-package', 
'/home/username/.config/sublime-text-3/Installed Packages/Emmet.sublime-package/emmet_completions', 
'/home/username/.config/sublime-text-3/Installed Packages/Emmet.sublime-package/emmet', 
'/home/username/.config/sublime-text-3/Installed Packages/Javascript Beautify.sublime-package/libs', 
'/home/username/.config/sublime-text-3/Installed Packages/Javascript Beautify.sublime-package/libs/js-beautify/python', 
'/home/username/.config/sublime-text-3/Installed Packages/JsFormat.sublime-package/libs', 
'/home/username/.config/sublime-text-3/Installed Packages/JsFormat.sublime-package/src', 
'/home/username/.config/sublime-text-3/Installed Packages/SqlBeautifier.sublime-package', 
'/home/username/.config/sublime-text-3/Packages/CodeFormatter/codeformatter/lib', 
'/home/username/.config/sublime-text-3/Packages/CodeFormatter/codeformatter/lib/htmlbeautifier', 
'/usr/lib/python35.zip', 
'/usr/lib/python3.5', 
'/usr/lib/python3.5/plat-x86_64-linux-gnu', 
'/usr/lib/python3.5/lib-dynload', 
'/usr/local/lib/python3.5/dist-packages', 
'/usr/lib/python3/dist-packages', 
'/home/username/.config/sublime-text-3/Packages/EncodingHelper/Codecs33-linux-x64/lib']

>>> import urllib.parse as url_parser
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'parse'

```

Package control 3.2.1
All plugins are updated
DoxyDoxygen still broken

**Comment by 20Tauri** [comment]
Using last version, DoxyDoxygen raises an error but continue to work...

I saw your post on the [Sublime Text forum](https://forum.sublimetext.com/t/dev-build-3121/22806/64). It's probably the best place to have support...

Something strange... Only linux based version seem to be affected... and versions prior to 3120 have no problem... Usualy unable package control "solve" the problem (check on your config, this may help Will Bond to locate the root cause)

**Comment by corderogerardo** [comment]
I solve this problem by doing Satisfy Dependencies in Preferences > Package Control. But my not work for everyone.

**Comment by 20Tauri** [comment]
Thank for reporting. As this problem persist... I will delay error and add an option "warn_on_network_import_failures" to hide it...

Hope the Sublime Text team will found and solve the root cause quickly...
It's really annoying for affected people

**Comment by pcaro** [comment]
The problem persist in my enviroment.

**Comment by 20Tauri** [comment]
Thank for your feedback

Sad news, as you can read here, this is not a bug in this plugin, but a bug in SublimeText.
To re-check it, please:

- make a fresh install of SublimeText.
- open the console
- type `import  urllib.parse as url_parser`

Once, you will reproduce the problem. As the plugin is not install, you will be sure that Sublime Text itself cause the problem. Then, please report it the the Sublime Text team... If a lot of people report it with their specific environment, perhaps they can detect the root cause...

This problem seem affect only Linux user (and perhaps only Ubuntu based on). Don't forget to give them a full description of your system.

As it's a non trivial bug (first detected in 3121), I've add a specific option `warn_on_network_import_failures` to hide the import error. All network functions (translations, internal bug report) will be silently disabled while the error persist.

This bug is really annoying for me, and for this plugin...
As DoxyDoxygen was the first plugin that detect it, I've received a lot of bug reports, I've also made a first analyze...  And, it probably still give a poor image of this plugin for new comers... and it forbids users like you some features (in this plugin and in others)
