### ISSUE TITLE
Question: How to choose between JSDoc @param tag layout

### ISSUE THREAD

**Issue by brenwell** [20Tauri/DoxyDoxygen#79]
Hello. 
First up, awesome tool, so thanks.

Quick question, according to the JSDoc Documentation there are 2 valid arrangements for the @param tag - with & without a hyphen. By default when I generate comments with sublime it autofills without hyphens. I personally find the hyphen version easier to read. Is there anyway to get hyphens by default? Thanks

## From the JSDoc documentation
http://usejsdoc.org/tags-param.html 

**Name, type, and description**
```js
/**
 * @param {string} somebody Somebody's name.
 */
function sayHello(somebody) {
    alert('Hello ' + somebody);
}
```
You can add a hyphen before the description to make it more readable. Be sure to include a space before and after the hyphen.

**Name, type, and description, with a hyphen before the description**
```js

/**
 * @param {string} somebody - Somebody's name.
 */
function sayHello(somebody) {
    alert('Hello ' + somebody);
}
```

**Comment by BITespresso** [comment]
I'd also like to have the ability to let doxydoxygen add the hyphen for JSDoc comments.

Is there something I could help to implement this?

**Comment by 20Tauri** [comment]
Unfortunatly not directly...
Of course you can create your own DocStyle and set parameters for the `@param` to something like
```python
 '\t\\{<type>\\} - <parameter_name>\t{ parameter_description }'
```
but it's sound a bit tricky and you will be blocked by a bug (space in token were not supported even on the last version). This will but fixed in the next one.

Once done (this can be done quickly), a custom DocStyle will work...

But it sound a non trivial way to do it... I have planned to make each DocStyle command configurable with a json file... It's a long and boring job (there's a lot of DocStyles), but it will make the plugin really more powerful. 
I will consider to implement it partially (including JsDoc)... But even partially it may take time...

**Comment by 20Tauri** [comment]
A new parameter "doc_styles" has been introduced in 0.69.3.
As example, you can found the line to configure the plugi as you want (https://github.com/20Tauri/DoxyDoxygen/releases/tag/0.69.3)

This feature is EXPERIMENTAL (and JsDoc only)
