### ISSUE TITLE
change my default comment style in Python

### ISSUE THREAD

**Issue by cs01** [20Tauri/DoxyDoxygen#92]
Just discovered this today, it's amazing!

I'm trying to auto-document python code. How do I switch the default comment style from 

```python
##
## @brief      { function_description }
##
## @param      sleep_time  { parameter_description }
## @param      kwargs      { parameter_description }
##
## @return     { description_of_the_return_value }
##
def some_fn(sleep_time=1, **kwargs):
```

to this

```python
def some_fn(sleep_time=1, **kwargs):
    """
    description
    
    @param      sleep_time  { parameter_description }
    @param      kwargs      { parameter_description }
    
    @return     { description_of_the_return_value }
    """
```

I tried various `doc_styles` in custom settings but none worked:
```json
// Settings in here override those in "${packages}/DoxyDoxygen/Doxy.sublime-settings",
// and are overridden in turn by syntax-specific settings.
{

    "python_func_annotations_are_types": false,
    "autofill_rules_default": [
        {
            "languages":  [ "python", "cython" ],
            "parsers":    [ "LanguagePython" ],
            "doc_styles": [ "Doxygen" ] // or "ApiDoc", "Sphinx" (you may consider Breathe's Doc)
        },
    ]
}
```

**Comment by 20Tauri** [comment]
Short answer: not possible

Long answer. DocString is a style of comment. But don't try to set `preferred_comments_styles`, this will not work. Why ? Because the command `comment_nearest_entity` (called on <kbd>Alt</kbd>+<kbd>Q</kbd> not consider "docstring" on creation. But, press <kbd>Alt</kbd>+<kbd>Q</kbd> with an existing comment will update it.

For now, your best option is probably to type `"""`+<kbd>Enter</kbd>

Remark: I don't know any Doxygen parser that extract documentation from DocStrings. DocStrings are usually used with "doc_styles" Sphinx or ApiDoc

**Comment by cs01** [comment]
> Remark: I don't know any Doxygen parser that extract documentation from DocStrings. DocStrings are usually used with "doc_styles" Sphinx or ApiDoc

Fair enough. I am using this extension for adding doxygen-style commetns to C/C++ code, and when I use python I just use docstrings, not doxygen, so I prefer that format.

Awesome tool, thanks for sharing it with the community.

**Comment by 20Tauri** [comment]
Thanks for using this tool (the community around this software is awesome, and you are a part of them)

With the last version (0.63.0), <kbd>Alt</kbd>+<kbd>Q</kbd> can now create docstring. Please refer to #96 for further informations.
