### ISSUE TITLE
[C++] Unable to generate doxygen comments for constructor and destructor when there is DLL macros

### ISSUE THREAD

**Issue by jasjuang** [20Tauri/DoxyDoxygen#95]
Say I have a class with the constructor and destructor like below

```
   explicit ArucoMarker(const cv::Ptr<cv::aruco::Dictionary> dictionary);

   ~ArucoMarker();
```

If I type alt+Q everything works without a problem

```
  /**
    * @brief      { function_description }
    *
    * @param[in]  dictionary  The dictionary
    */
   explicit ArucoMarker(const cv::Ptr<cv::aruco::Dictionary> dictionary);

   /**
    * @brief      Destroys the object.
    */
   ~ArucoMarker();
```

However, to make code compatible with windows, typically there will be a DLL macro in front.

```
  #ifdef WIN32
  #define WINDOWS_DLL __declspec(dllexport)
  #else
  #define WINDOWS_DLL
  #endif

  WINDOWS_DLL explicit ArucoMarker(const cv::Ptr<cv::aruco::Dictionary> dictionary);

  WINDOWS_DLL ~ArucoMarker();
```

When I type alt+Q on the constructor and destructor, no doxygen comments show up. Would appreciate if you can fix this!

**Comment by 20Tauri** [comment]
In your example, I assume "ArucoMarker" is in a "class ArucoMarker" block
If not, may partially explain the problem.
With the current DoxyDoxygen version (0.62.0), the second example should detect a "function". If not you probably also have a problem with your C++ grammar (you can check the sublime text scope_name to confirm)

The first case, is not properly handled (even if "explicit" remove the ambiguity)

Both will be fixed in the next release.
But once again, you probably also have a probably with your c++ grammar (so `/**` will work but not <kbd>Alt</kbd>+<kbd>Q</kbd>)

Note: If you want to export a whole class, you can also add WINDOWS_DLL on the class direclty instead of function).

**Comment by jasjuang** [comment]
Yes it is inside a "class ArucoMarker" block. I was simplifying things. It should be

```
  #ifdef WIN32
  #define WINDOWS_DLL __declspec(dllexport)
  #else
  #define WINDOWS_DLL
  #endif

class ArucoMarker
{
 public:
  WINDOWS_DLL explicit ArucoMarker(const cv::Ptr<cv::aruco::Dictionary> dictionary);

  WINDOWS_DLL ~ArucoMarker();
};
```

Visual studio will having compilation warnings if I have something private if I put WINDOWS_DLL on the class directly hence I wasn't doing it.

Thanks again and I look forward to the next release!

EDIT: To be precise it's warning C4251

**Comment by 20Tauri** [comment]
Fixed in evolution branch

**Comment by jasjuang** [comment]
Tried and it is fixed for me, thanks!
